services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gym-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  web:
    image: gym-app:1.0
    build:
      context: .
      dockerfile: GYM/Dockerfile
    container_name: gym-web
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_HTTPS_REDIRECT=true
      - "ConnectionStrings__CadenaSQL=Server=db,1433;Database=GYM;User ID=sa;Password=Your_password123;TrustServerCertificate=True;Encrypt=True;MultipleActiveResultSets=True;"
    ports:
      - "8080:8080"

volumes:
  mssql_data: